import React from 'react';
import { ROIResult } from '../types';
import { KPICard } from './KPICard';
import { ChartsSection } from './ChartsSection';
import { ESGGrid } from './ESGGrid';
import { DetailTable } from './DetailTable';
import { AnimatedNumber } from './AnimatedNumber';
import { Coins, TrendingUp, Timer, Sparkles } from 'lucide-react';
import { formatCurrency } from '../utils';

interface PdfReportProps {
    result: ROIResult;
    scalingData: Array<{ contracts: number; saving: number }>;
    contractCount: number;
}

export const PdfReport: React.FC<PdfReportProps> = ({ result, scalingData, contractCount }) => {
    return (
        <div
            id="pdf-report-root"
            className="w-[794px] bg-white text-slate-700 font-sans p-10 space-y-8"
        >
            <section className="text-center">
                <h2 className="text-slate-400 text-xs font-bold tracking-widest uppercase mb-3 flex items-center justify-center gap-3">
                    <span className="w-8 h-px bg-slate-300"></span>
                    연간 예상 비용 절감액
                    <span className="w-8 h-px bg-slate-300"></span>
                </h2>
                <div className="text-6xl font-black text-slate-900 tracking-tighter flex items-center justify-center gap-2 whitespace-nowrap">
                    <span className="text-brand-600">₩</span>
                    <AnimatedNumber value={result.netSaving} format={formatCurrency} animate={false} />
                </div>
                <p className="mt-4 text-slate-500 max-w-xl mx-auto text-sm leading-relaxed">
                    기존 서면 계약 대비 예상되는 <strong className="text-slate-800 font-semibold">연간 순수 절감액</strong>입니다.
                    <br />
                    <span className="text-brand-600 font-medium">인건비, 등기 우편료, 종이 보관 비용</span>을 포함하여 산출되었습니다.
                </p>
            </section>

            <section className="grid grid-cols-4 gap-4 break-inside-avoid">
                <KPICard
                    title="연간 순수 절감액"
                    value={result.netSaving}
                    format={formatCurrency}
                    suffix="원"
                    subValue={`${Math.round((result.netSaving / result.totalBefore) * 100)}% 절감`}
                    icon={Coins}
                    colorClass="text-accent-teal"
                    isPdf={true}
                />
                <KPICard
                    title="투자 수익률 (ROI)"
                    value={result.roiPercent}
                    suffix="%"
                    subValue={`${(result.roiPercent / 100).toFixed(1)}배 효율`}
                    icon={TrendingUp}
                    colorClass="text-brand-600"
                    isPdf={true}
                />
                <KPICard
                    title="비용 회수 기간"
                    value={result.paybackDays}
                    format={(v) => v < 1 ? "즉시" : v < 30 ? `${Math.ceil(v)}일` : `${(v / 30).toFixed(1)}개월`}
                    subValue={result.paybackDays < 30 ? "초단기 회수" : "빠른 회수"}
                    icon={Timer}
                    colorClass="text-accent-amber"
                    isPdf={true}
                />
                <KPICard
                    title="업무 시간 단축"
                    value={result.daysSaved}
                    suffix="일"
                    subValue="99% 감소"
                    icon={Sparkles}
                    colorClass="text-accent-rose"
                    isPdf={true}
                />
            </section>

            <section className="grid grid-cols-2 gap-6 break-inside-avoid">
                <div className="bg-white border border-slate-200 rounded-2xl p-1 overflow-hidden shadow-soft">
                    <ChartsSection result={result} scalingData={scalingData} isPdf={true} />
                </div>
                <ESGGrid result={result} contractCount={contractCount} isPdf={true} />
            </section>

            <section className="bg-white border border-slate-200 rounded-2xl p-8 break-inside-avoid shadow-soft">
                <DetailTable result={result} isPdf={true} />
            </section>

            <footer className="text-center text-slate-400 text-[10px] pt-6 border-t border-slate-100">
                <p className="mb-2">
                    기준 요약: 대면 120,000원/건(교통 5만 + 숙박 5만 + 식비 2만), 등기 16,830원/건(버스 3,000 + 등기 3,800 + 시급 10,030),
                    전자서명 800원/건(예시), ESG 산출은 KEI 기준.
                </p>
                <p>본 시뮬레이션 결과는 입력하신 값을 바탕으로 추산된 예상치이며, 실제 도입 효과와는 차이가 있을 수 있습니다.</p>
                <p className="mt-1">Copyright © FORCS CO., LTD. All rights reserved.</p>
                <p className="mt-1">Generated by eformsign ROI Simulator</p>
            </footer>
        </div>
    );
};
